POST http://localhost:8085/task
Content-Type: application/json

{
  "content": "Bozorga borish"
}

###

GET http://localhost:8085/task
Content-Type: application/json

###

PUT http://localhost:8085/task/update/4028818b81cb7b460181cb7b5e310000
Content-Type: application/json

{
  "content": "Darsga borish"
}

###

DELETE http://localhost:8085/task/delete/4028818b81cb76230181cb7630070000

###

PUT http://localhost:8085/task/finishTask/4028818b81cb7b460181cb7b5e310000