POST http://localhost:8085/task
Content-Type: application/json

{
  "content": "Sayr qilish"
}

###

GET http://localhost:8085/task
Content-Type: application/json

###

PUT http://localhost:8085/task/update/8a8a855c81f7bdbb0181f7c0904d0004
Content-Type: application/json

{
  "content": "Futbol o'ynash"
}

###

DELETE http://localhost:8085/task/delete/8a8a855c81f7bdbb0181f7c0904d0004

###

PUT http://localhost:8085/task/finishTask/8a8a855c81f7bdbb0181f7c0904d0004

###

GET http://localhost:8085/task/find/4